version: '3.9'

services:
  app:
    build: .
    container_name: app-server
    restart: always
    volumes:
      - .:/code
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    env_file: 
      - .env